import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
padding = { x = 25, y = 20 }
dynamic_title = false
dimensions = { columns = 110, lines = 35 }

[scrolling]
history = 100000

[font]
normal = { family = "ZedMono Nerd Font Mono", style = "Extended" }
italic = { style = "Extended Itatic" }
bold = { style = "Extended Medium" }
bold_italic = { style = "Extended Medium Italic" }
size = 13.4

[cursor]
style = { shape = "Beam", blinking = "On" }
