# import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
live_config_reload = true

[colors.primary]
background = "#1f2430"
foreground = "#cbccc6"
bright_foreground = "#f28779"

[colors.normal]
black = "#212733"
red = "#f08778"
green = "#53bf97"
yellow = "#fdcc60"
blue = "#60b8d6"
magenta = "#ec7171"
cyan = "#98e6ca"
white = "#fafafa"

[colors.bright]
black = "#686868"
red = "#f58c7d"
green = "#58c49c"
yellow = "#ffd165"
blue = "#65bddb"
magenta = "#f17676"
cyan = "#9debcf"
white = "#ffffff"

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
padding = { x = 25, y = 20 }
dynamic_title = false
dimensions = { columns = 110, lines = 35 }

[scrolling]
history = 100000

[font]
normal = { family = "ZedMono Nerd Font Mono", style = "Extended" }
italic = { style = "Extended Itatic" }
bold = { style = "Extended Medium" }
bold_italic = { style = "Extended Medium Italic" }
size = 13.4

[cursor]
style = { shape = "Beam", blinking = "On" }
